- name: Build, Push and Run Docker image for the Python application
  hosts: localhost
  become: no

  vars:
    image_name: "bbebin/python-app"
    image_tag: "0.3"
    app_directory: "/tmp//app"
    listen_ports: "5000:5000"

  tasks:
    - name: Create application directory
      file:
        path: "{{ app_directory }}" 
        state: directory
        mode: 0755
    
    - name: Git Checkout
      git:
        repo: git@github.com:borislavbebin/devops-programme
        dest: "{{ app_directory }}"
        version: ansible
        update: yes

    - name: Build Docker Image
      docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        path: "{{ app_directory }}"

    - name: Run Docker Container
      docker_container:
        name: "python flask app"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        ports: "{{ listen_ports }}"
