name: Pytohn CI


on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.X"

  editorconfig:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run EditorConfig Checker
        uses: editorconfig-checker/action-editorconfig-checker@main

  pylint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # upgrade pip
          python -m pip install --upgrade pip

          # install requirements
          python -m pip install -r ./requirements.txt

          # install pylint
          python -m pip install black pylint

      - name: Analyzing the code with pylint
        run: |
          pylint --rcfile='./.pylintrc' $(git ls-files './app')

      - name: Lint with Markdown-lint
        uses: articulate/actions-markdownlint@v1
        with:
          files: './*.md'
          ignore: node_modules
          version: 0.28.1

  unit_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # upgrade pip
          python -m pip install --upgrade pip

          # install dependencies
          python -m pip install -r ./requirements.txt

      - name: Execute unit-test
        run: |
          python -m unittest discover -s ./app -p "*_test.py"

  secrets_scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and Install GitLeaks
        run: |
          curl -sL https://github.com/gitleaks/gitleaks/releases/download/v8.18.1/gitleaks_8.18.1_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xzvf gitleaks.tar.gz
          mv gitleaks /usr/local/bin/
          chmod +x /usr/local/bin/gitleaks

      - name: Scan for Secrets
        run: gitleaks -f json -r gitleaks-report.json

      - name: Upload gitleaks findings
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-findings
          path: ./gitleaks-report.json

  sonarcloud:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarCloud Scanner
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  snyk-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Snyk
        run: npm install -g snyk

      - name: Run Snyk SCA
        run: |
          python -m pip install -r ./requirements.txt
          snyk test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker-image-build-scan-push:
    runs-on: ubuntu-latest
    needs: [build, editorconfig, pylint, unit_test, secrets_scan, sonarcloud, snyk-scan]
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Build docker image
        run: docker build -t facelessbob/python-app:${{ github.sha }} .

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'facelessbob/python-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: DockerHub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker image push
        run: docker push facelessbob/python-app:${{ github.sha }}
