name: Pytohn CI


on: [push]

jobs:
  pipe_setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ["3.X"]

      - name: Install dependencies
        run: |
          # upgrade pip
          python -m pip install --upgrade pip
          
          # install dependencies
          python -m pip install -r ./requirements.txt
          
          # install pylint
          python -m pip install black pylint

          # Install gitleaks
          curl -sL https://github.com/zricethezav/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: setup
          path: .

  editorconfig:
    needs: pipe_setup
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: setup

      - name: Use Artifact
        run: |
          # Access all downloaded files
          ls -R setup

      - name: Run EditorConfig Checker
        uses: editorconfig-checker/action-editorconfig-checker@main

  pylint:
    needs: pipe_setup
    runs-on: ubuntu-20.04
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: setup

      - name: Use Artifact
        run: |
          # Acess all downloaded artifacts
          ls -R setup
        
      - name: Analyzing the code with pylint
        run: |
          pylint --rcfile='./.pylintrc' $(git ls-files './app')

      - name: Lint with Markdown-lint
        uses: articulate/actions-markdownlint@v1
        with:
          files: './*.md'
          ignore: node_modules
          version: 0.28.1

  unit_test:
    needs: pipe_setup
    runs-on: ubuntu-20.04
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: setup

      - name: Use Artifact
        run: |
          ls -R setup

      - name: Execute unit-test
        run: |
          python -m unittest discover -s ./app -p "*_test.py"

  secrets_scan:
    needs: pipe_setup
    runs-on: ubuntu-20.04
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          setup

      - name: Use Artifact
        runs: |
          ls -R setup

      - name: Scan for Secrets
        run: gitleaks --path . --redact

      - name: Upload gitleaks findings
        uses: actions/upload-artifact@v2
        with:
          name: gitleaks-findings
          path: ./gitleaks-report.json

