name: Pytohn CI


on: [push]

jobs:
  editorconfig:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run EditorConfig Checker
        uses: editorconfig-checker/action-editorconfig-checker@main

  pylint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.X"

      - name: Install dependencies
        run: |
          # upgrade pip
          python -m pip install --upgrade pip

          # install requirements
          python -m pip install -r ./requirements.txt

          # install pylint
          python -m pip install black pylint

      - name: Analyzing the code with pylint
        run: |
          pylint --rcfile='./.pylintrc' $(git ls-files './app')

      - name: Lint with Markdown-lint
        uses: articulate/actions-markdownlint@v1
        with:
          files: './*.md'
          ignore: node_modules
          version: 0.28.1

  unit_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.X"

      - name: Install dependencies
        run: |
          # upgrade pip
          python -m pip install --upgrade pip

          # install dependencies
          python -m pip install -r ./requirements.txt

      - name: Execute unit-test
        run: |
          python -m unittest discover -s ./app -p "*_test.py"

  secrets_scan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download and Install GitLeaks
        run: |
          curl -sL https://github.com/gitleaks/gitleaks/releases/download/v8.18.1/gitleaks_8.18.1_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xzvf gitleaks.tar.gz
          mv gitleaks /usr/local/bin/
          chmod +x /usr/local/bin/gitleaks

      - name: Scan for Secrets
        run: gitleaks .

      - name: Upload gitleaks findings
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-findings
          path: ./gitleaks-report.json
